import { BrowserPendingSubmissionCommands, isProvenPreEffectBrowserSubmissionError } from "./pending-submissions.js";

export const CONTROLS_SCRIPT = String.raw`(()=>{
"use strict";
const state={bearer:"",csrf:"",runs:[],selected:null,attention:[],history:[],decision:null,sourceTexts:{},cursor:0,connected:false};
const MAX_SOURCE_DISPLAY_CHARS=65536;
const MAX_PENDING_BROWSER_SUBMISSIONS=32;
const BrowserPendingSubmissionCommands=${BrowserPendingSubmissionCommands.toString()};
const isProvenPreEffectBrowserSubmissionError=${isProvenPreEffectBrowserSubmissionError.toString()};
const pendingSubmissions=new BrowserPendingSubmissionCommands(()=>crypto.randomUUID());
const UI_ACTOR={actorId:"zentra-local-operator",channel:"ui"};
const $=(id)=>document.getElementById(id);
const setText=(node,value)=>{node.textContent=value==null?"":String(value)};
const status=(message,tone="")=>{const node=$("status");setText(node,message);node.dataset.tone=tone};
const request=async(path,options={})=>{
  const headers={accept:"application/json",...(options.headers||{})};
  if(state.bearer)headers.authorization="Bearer "+state.bearer;
  if(options.method&&options.method!=="GET")headers["x-csrf-token"]=state.csrf;
  const response=await fetch(path,{...options,headers,credentials:"omit",cache:"no-store"});
  const body=await response.json().catch(()=>({error:"invalid_response"}));
  if(!response.ok){const error=new Error(body.error||"request_failed");error.code=body.error;throw error}
  return body;
};
const value=(object,names,fallback="")=>{for(const name of names)if(object&&object[name]!=null)return object[name];return fallback};
const currentRun=()=>state.selected&&(state.selected.run||state.selected);
const list=(result,names)=>{if(Array.isArray(result))return result;for(const name of names)if(Array.isArray(result&&result[name]))return result[name];return[]};
const badge=(text)=>{const node=document.createElement("span");node.className="badge";setText(node,text);return node};
const field=(term,description)=>{const row=document.createElement("div");row.className="fact";const dt=document.createElement("dt");const dd=document.createElement("dd");setText(dt,term);setText(dd,description);row.append(dt,dd);return row};
const label=(value,fallback="Unknown")=>typeof value==="string"&&value?value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase()):fallback;
const renderRuns=()=>{
  const host=$("runs");host.replaceChildren();
  if(!state.runs.length){const empty=document.createElement("p");empty.className="empty";setText(empty,"No runs yet. Submit a goal or ticket folder to begin.");host.append(empty);return}
  for(const run of state.runs){const button=document.createElement("button");button.type="button";button.className="run-card";const id=value(run,["runId","id"],"Unknown run");button.dataset.selected=String(id===value(state.selected,["runId","id"]));const title=document.createElement("strong");setText(title,value(run,["title","goal","summary"],id));const meta=document.createElement("span");setText(meta,id);button.append(title,meta,badge(value(run,["state","status","lifecycle"],"queued")));button.addEventListener("click",()=>selectRun(id));host.append(button)}
};
const appendJson=(host,label,data)=>{if(data==null)return;const details=document.createElement("details");const summary=document.createElement("summary");setText(summary,label);const pre=document.createElement("pre");setText(pre,JSON.stringify(data,null,2));details.append(summary,pre);host.append(details)};
const sourceKey=(runId,sourceId)=>runId+"\u0000"+sourceId;
const renderLoadedSource=(output,cached)=>{const pre=document.createElement("pre");pre.className="ticket-text";setText(pre,cached.text);output.replaceChildren(pre);if(cached.truncated){const notice=document.createElement("p");notice.className="notice";setText(notice,"Text display truncated at "+MAX_SOURCE_DISPLAY_CHARS+" characters. Download is not exposed by this view.");output.append(notice)}};
const loadSourceText=async(runId,source,output,button)=>{const key=sourceKey(runId,source.sourceId);if(state.sourceTexts[key]?.loading===true)return;state.sourceTexts[key]={loading:true};button.dataset.loading="true";button.disabled=true;setText(button,"Loading source text");try{const result=await request("/api/v1/zentra/runs/"+encodeURIComponent(runId)+"/sources/"+encodeURIComponent(source.sourceId)+"/text");if(result.runId!==runId||result.sourceId!==source.sourceId||result.digest!==source.digest||result.sizeBytes!==source.sizeBytes||result.mediaType!==source.mediaType||result.trust!==source.trust)throw new Error("source_binding_mismatch");const text=String(result.text);const cached={text:text.slice(0,MAX_SOURCE_DISPLAY_CHARS),truncated:text.length>MAX_SOURCE_DISPLAY_CHARS};state.sourceTexts[key]=cached;const currentOutput=$(output.id);const currentButton=$(button.id);if(currentOutput)renderLoadedSource(currentOutput,cached);if(currentButton){currentButton.disabled=true;setText(currentButton,"Source text loaded")}status("Loaded verified source text.","ok")}catch(error){delete state.sourceTexts[key];const currentButton=$(button.id);if(currentButton){currentButton.disabled=false;setText(currentButton,"Retry source text")}status("Source text unavailable: "+error.message+".","error")}};
const renderTicketSources=(host,runId,intake)=>{for(const source of intake?.sources||[]){const section=document.createElement("section");section.className="source-card";const heading=document.createElement("h4");setText(heading,value(source,["relativePath","sourceId"],"Source"));const facts=document.createElement("dl");facts.className="facts";facts.append(field("Source ID",source.sourceId),field("Size",source.sizeBytes+" bytes"),field("Media type",source.mediaType),field("Trust",source.trust),field("Digest",source.digest));const safeId=source.sourceId.replace(/[^A-Za-z0-9_-]/g,"-");const output=document.createElement("div");output.id="source-text-"+safeId;const button=document.createElement("button");button.id="source-button-"+safeId;button.type="button";button.className="secondary";button.setAttribute("aria-controls",output.id);const cached=state.sourceTexts[sourceKey(runId,source.sourceId)];if(cached?.loading===true){button.dataset.loading="true";button.disabled=true;setText(button,"Loading source text")}else if(cached){renderLoadedSource(output,cached);button.disabled=true;setText(button,"Source text loaded")}else setText(button,"Expand source text");button.addEventListener("click",()=>loadSourceText(runId,source,output,button));section.append(heading,facts,button,output);host.append(section)}};
const renderRun=()=>{
  const host=$("run-detail");host.replaceChildren();
  const detail=state.selected;const run=currentRun();
  if(!run){const empty=document.createElement("p");empty.className="empty";setText(empty,"Select a run to inspect source, analysis, plan, and authority readiness.");host.append(empty);return}
  const intake=detail.intake||{};const analysis=detail.analysis||{};const readiness=detail.planning?.readiness||{};const lifecycle=String(value(run,["lifecycle","state","status"],"unknown"));const terminalOutcome=value(run,["terminalOutcome"],null);
  const heading=document.createElement("h3");setText(heading,value(run,["title","goal","summary"],value(run,["runId","id"],"Run")));const facts=document.createElement("dl");facts.className="facts";
  facts.append(field("Run",value(run,["runId","id"])),field("Lifecycle",label(lifecycle)),field("Terminal outcome",terminalOutcome===null?"Not terminal":label(terminalOutcome)),field("Source kind",label(intake.sourceKind,"Pending")),field("Source count",Number.isSafeInteger(intake.sourceCount)?String(intake.sourceCount):"0"),field("Analysis status",label(analysis.status,"Not started")),field("Analysis rounds",Array.isArray(analysis.rounds)?String(analysis.rounds.length):"0"),field("Readiness",readiness.ready===true?"Ready":"Waiting"),field("Approval",label(readiness.approvalState,"Waiting")));
  host.append(heading,facts);
  const stateName=lifecycle.toLowerCase();
  if(["degraded","waiting","stale","rejected"].some(name=>stateName.includes(name))||terminalOutcome!==null){const notice=document.createElement("p");notice.className="notice";setText(notice,terminalOutcome===null?"Run is "+label(stateName)+". Review the retained evidence before taking another action.":"Run ended with "+label(terminalOutcome)+". Retained evidence remains available for review.");host.append(notice)}
  renderTicketSources(host,value(run,["runId","id"]),detail.intake);appendJson(host,"Source and provenance",detail.intake||run.source);
  appendJson(host,"Analysis and questionnaire",detail.analysis||run.analysis||run.questionnaire);
  appendJson(host,"Plan DAG",detail.planning?.dag||run.plan||run.dag);
  appendJson(host,"Authority envelope",detail.planning?.envelope||run.envelope||run.authorityEnvelope);
  appendJson(host,"Readiness evidence",detail.planning?.readiness||run.readinessEvidence);
  $("cancel-run").disabled=stateName==="terminal"||terminalOutcome!==null;
};
const renderAttention=()=>{
  const host=$("attention");host.replaceChildren();
  if(!state.attention.length){const empty=document.createElement("p");empty.className="empty";setText(empty,"No operator decisions are waiting.");host.append(empty);return}
  for(const item of state.attention){const button=document.createElement("button");button.type="button";button.className="attention-card";const id=value(item,["decisionId","id"]);const title=document.createElement("strong");setText(title,value(item,["title","question","kind"],"Decision"));button.append(title,badge(value(item,["status","state"],"pending")));button.addEventListener("click",()=>loadDecision(id));host.append(button)}
};
const renderHistory=()=>{const host=$("decision-history");host.replaceChildren();if(!state.history.length){const empty=document.createElement("p");empty.className="empty";setText(empty,"No resolved decisions yet.");host.append(empty);return}for(const item of state.history){const card=document.createElement("article");card.className="history-card";const packet=item.packet||{};const heading=document.createElement("strong");setText(heading,value(packet,["summary","question"],label(item.kind,"Decision")));const statusName=label(item.status);const actor=item.resolution?.actor;const meta=document.createElement("p");setText(meta,actor?statusName+" by "+actor.actorId+" via "+actor.channel:statusName);card.append(heading,badge(statusName),meta);host.append(card)}};
const renderDecision=()=>{
  const host=$("decision");host.replaceChildren();const decision=state.decision;
  if(!decision){const empty=document.createElement("p");empty.className="empty";setText(empty,"Choose an attention item to answer or review.");host.append(empty);return}
  const packet=decision.packet||{};const heading=document.createElement("h3");setText(heading,value(packet,["summary","question"],value(decision,["title","question","kind"],"Operator decision")));const prompt=document.createElement("p");setText(prompt,value(packet,["question","expectedEffect","proposedStateChange"],value(decision,["prompt","question","summary"])));host.append(heading,prompt);
  const recommendation=value(decision,["recommendation","recommendedAnswer"],null);if(recommendation!==null){const note=document.createElement("p");note.className="recommendation";const recommendationText=typeof recommendation==="string"?recommendation:[recommendation.optionId,recommendation.rationale].filter(part=>typeof part==="string").join(" - ");setText(note,"Recommendation: "+recommendationText+". No response has been selected.");host.append(note)}
  appendJson(host,"Impacts",decision.impacts);
  appendJson(host,"Plan DAG",decision.plan||decision.dag);
  appendJson(host,"Authority envelope",decision.envelope||decision.authorityEnvelope);
  const statusName=String(value(decision,["status","state"],"pending")).toLowerCase();if(statusName!=="pending"){const notice=document.createElement("p");notice.className="notice";setText(notice,"This decision is "+statusName+" and cannot be submitted again.");host.append(notice);return}
  const kind=String(value(decision,["kind","type"],"question")).toLowerCase();
  if(kind.includes("approval")||kind.includes("plan")||decision.plan||decision.envelope){host.append($("plan-actions").content.cloneNode(true));const planning=state.selected?.planning||{};const plan=String(value(packet,["planDigest"],planning.planDigest||""));const envelope=String(value(packet,["envelopeDigest"],planning.envelopeDigest||""));setText($("decision").querySelector("[data-plan-digest]"),plan);setText($("decision").querySelector("[data-envelope-digest]"),envelope)}else{host.append($("question-actions").content.cloneNode(true));const select=$("decision").querySelector("[name=optionId]");for(const option of decision.options||[]){const node=document.createElement("option");node.value=String(option.optionId);setText(node,value(option,["label","title","description","optionId"]));select.append(node)}}
};
const captureInteraction=()=>{const controls={};for(const control of document.querySelectorAll("input[id],textarea[id],select[id]")){controls[control.id]={value:control.value,checked:control.checked===true,start:control.selectionStart,end:control.selectionEnd}}const active=document.activeElement instanceof HTMLElement?document.activeElement.id:"";return {controls,active,decisionId:state.decision?.decisionId||null}};
const restoreInteraction=(snapshot)=>{for(const [id,saved] of Object.entries(snapshot.controls)){const control=$(id);if(!(control instanceof HTMLInputElement||control instanceof HTMLTextAreaElement||control instanceof HTMLSelectElement))continue;control.value=saved.value;if("checked" in control)control.checked=saved.checked;if(typeof saved.start==="number"&&typeof control.setSelectionRange==="function")control.setSelectionRange(saved.start,saved.end)}if(snapshot.active)$(snapshot.active)?.focus()};
const refresh=async()=>{const interaction=captureInteraction();const result=await request("/api/v1/zentra/runs");state.runs=list(result,["runs","items"]);renderRuns();if(state.selected){const id=value(currentRun(),["runId","id"]);await selectRun(id,false,interaction.decisionId)}else if(state.runs.length){await selectRun(value(state.runs[0],["runId","id"]),false,interaction.decisionId)}restoreInteraction(interaction);window.__consoleSections.overview?.render?.()};
const selectRun=async(id,announce=true,decisionId=null)=>{const base="/api/v1/zentra/runs/"+encodeURIComponent(id);state.selected=await request(base);state.attention=list(state.selected,["attention"]).filter(item=>item.status==="pending");state.history=list(state.selected,["decisions"]).filter(item=>item.status!=="pending");renderRuns();renderRun();renderAttention();renderHistory();state.decision=decisionId?await request("/api/v1/zentra/decisions/"+encodeURIComponent(decisionId)).catch(()=>null):null;renderDecision();window.__consoleSections.overview?.render?.();if(announce)status("Loaded run "+id+".","ok")};
const loadDecision=async(id)=>{state.decision=await request("/api/v1/zentra/decisions/"+encodeURIComponent(id));renderDecision();status("Decision loaded. Review all impacts before submitting.")};
const mutateDecision=async(action,body)=>{const id=value(state.decision,["decisionId","id"]);const command={...body,runId:state.decision.runId,expectedVersion:state.decision.streamVersion,commandId:crypto.randomUUID()};await request("/api/v1/zentra/decisions/"+encodeURIComponent(id)+"/"+action,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(command)});status("Decision recorded. Duplicate submission is disabled.","ok");await selectRun(value(currentRun(),["runId","id"]),false)};
const resetCursor=()=>{state.cursor=0;document.documentElement.dataset.eventCursor="0";status("Event history changed. Rebuilding projections from durable history.","error")};
const readChangePage=async()=>{const response=await fetch("/api/v1/zentra/events?cursor="+state.cursor,{headers:{accept:"text/event-stream",authorization:"Bearer "+state.bearer,"last-event-id":String(state.cursor)},credentials:"omit",cache:"no-store"});if(response.status===409){const failure=await response.json().catch(()=>({}));if(failure.error==="cursor_unavailable"){resetCursor();return {changed:true,hasMore:true}}}if(!response.ok)throw new Error("event_stream_failed");const reader=response.body.getReader();const decoder=new TextDecoder();let pending="";let changed=false;let hasMore=false;for(;;){const part=await reader.read();pending+=decoder.decode(part.value||new Uint8Array(),{stream:!part.done});const frames=pending.split("\n\n");pending=frames.pop()||"";for(const frame of frames){const id=/^id: ([0-9]+)$/m.exec(frame)?.[1];if(id){state.cursor=Number(id);document.documentElement.dataset.eventCursor=id}if(/^event: change$/m.test(frame)){changed=true;const data=/^data: (.+)$/m.exec(frame)?.[1];if(data){try{applyGatewayChange(JSON.parse(data))}catch{}}}if(/^event: page$/m.test(frame)){const data=/^data: (.+)$/m.exec(frame)?.[1];if(data){try{hasMore=JSON.parse(data).hasMore===true}catch{}}}}if(part.done)break}return {changed,hasMore}};
const synchronize=async()=>{let changed=false;let page;do{page=await readChangePage();changed=changed||page.changed}while(page.hasMore);if(changed)await refresh()};
const connect=async()=>{while(state.bearer){try{await synchronize();state.connected=true;$("connection").dataset.connected="true";setText($("connection"),"Live");await new Promise(resolve=>setTimeout(resolve,250))}catch{state.connected=false;$("connection").dataset.connected="false";setText($("connection"),"Reconnecting");await new Promise(resolve=>setTimeout(resolve,750))}}};
const handoff=async()=>{const fragment=location.hash;history.replaceState(null,"","/");document.documentElement.dataset.location=location.href;const token=fragment.startsWith("#token=")?decodeURIComponent(fragment.slice(7)):"";if(!token){status("This page needs a fresh one-time launch link.","error");return}try{const session=await fetch("/api/v1/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token}),credentials:"same-origin",cache:"no-store"});const result=await session.json();if(!session.ok)throw new Error(result.error||"session_failed");state.bearer=result.bearerToken;state.csrf=result.csrfToken;await refresh();await synchronize();status("Secure local session established.","ok");document.documentElement.dataset.ready="true";void connect()}catch(error){status("Session unavailable: "+error.message+".","error")}};
const submitRun=async(form,submission,message)=>{if(form.dataset.submitting==="true")return;form.dataset.submitting="true";const controls=[...form.querySelectorAll("button,input,textarea")];for(const control of controls)control.disabled=true;let command=null;try{command=pendingSubmissions.reserve(submission,UI_ACTOR);await request("/api/v1/zentra/runs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...submission,commandId:command.commandId})});pendingSubmissions.acknowledge(command);form.reset();status(message,"ok");await refresh()}catch(error){if(command&&isProvenPreEffectBrowserSubmissionError(error.code))pendingSubmissions.acknowledge(command);status("Submission failed: "+error.message+".","error")}finally{delete form.dataset.submitting;for(const control of controls)control.disabled=false}};
$("goal-form").addEventListener("submit",async(event)=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);await submitRun(form,{kind:"inline_goal",goal:data.get("goal")},"Goal submitted.")});
$("tickets-form").addEventListener("submit",async(event)=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);await submitRun(form,{kind:"ticket_directory",directoryPath:data.get("path")},"Ticket folder submitted.")});
$("cancel-run").addEventListener("click",async()=>{const run=currentRun();if(!run)return;try{await request("/api/v1/zentra/runs/"+encodeURIComponent(run.runId)+"/cancel",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({expectedVersion:run.streamVersion,commandId:crypto.randomUUID(),cancellationId:crypto.randomUUID(),reasonCode:"operator_requested"})});status("Cancellation requested.","ok");await refresh()}catch(error){status("Cancellation failed: "+error.message+".","error")}});
$("decision").addEventListener("submit",async(event)=>{event.preventDefault();const form=event.target;const data=new FormData(form);try{if(form.dataset.action==="answer")await mutateDecision("answer",{optionId:data.get("optionId")});if(form.dataset.action==="reject-question")await mutateDecision("reject-question",{reason:data.get("reason")});if(form.dataset.action==="approve-plan"){const planning=state.selected?.planning||{};const packet=state.decision.packet||{};const plan=String(value(packet,["planDigest"],planning.planDigest||""));const envelope=String(value(packet,["envelopeDigest"],planning.envelopeDigest||""));const confirmedPlan=String(data.get("planDigest")||"");const confirmedEnvelope=String(data.get("envelopeDigest")||"");if(!plan||!envelope||confirmedPlan!==plan||confirmedEnvelope!==envelope){status("Approval requires the exact displayed plan and envelope digests.","error");return}await mutateDecision("approve-plan",{planDigest:confirmedPlan,envelopeDigest:confirmedEnvelope})}if(form.dataset.action==="reject-plan")await mutateDecision("reject-plan",{reason:data.get("reason")})}catch(error){status("Decision failed: "+error.message+".","error")}});
window.__consoleSections=window.__consoleSections||{};window.__consoleSections.controls={refresh,connect};
})();`;

export const CONTROLS_MARKUP = `<section class="intake" aria-label="Run intake"><form id="goal-form" class="panel"><h2>Inline goal</h2><label class="field-label" for="goal">Goal</label><textarea id="goal" name="goal" required maxlength="20000" placeholder="Describe one measurable outcome"></textarea><p><button class="primary" type="submit">Submit goal</button></p></form><form id="tickets-form" class="panel"><h2>Ticket folder</h2><label class="field-label" for="ticket-path">Project-relative folder</label><div class="form-row"><div><input id="ticket-path" name="path" required maxlength="1024" placeholder="tickets/release-42"></div><button class="primary" type="submit">Submit tickets</button></div><p class="empty">The configured workflow validates path authority and bounded source ingestion.</p></form></section>
<section class="workspace" aria-label="Run operations"><section class="panel"><h2>Runs</h2><div id="runs" class="stack"></div></section><section class="panel"><h2>Run, source, analysis, and readiness</h2><div id="run-detail"></div><p><button id="cancel-run" class="danger" type="button" disabled>Cancel run</button></p></section><section class="panel"><h2>Pending attention</h2><div id="attention" class="stack" aria-live="polite"></div><div id="decision"></div><h3>Decision history</h3><div id="decision-history" aria-label="Resolved decision history"></div></section></section>
<template id="question-actions"><div class="decision-actions"><form data-action="answer"><label class="field-label" for="decision-option">Answer</label><select id="decision-option" name="optionId" required><option value="">Choose an answer</option></select><button class="primary" type="submit">Submit answer</button></form><form data-action="reject-question"><label class="field-label" for="question-reason">Rejection reason</label><input id="question-reason" name="reason" required maxlength="2000"><button class="danger" type="submit">Reject question</button></form></div></template>
<template id="plan-actions"><div class="decision-actions"><p id="digest-help">Type both complete digests below to confirm this exact plan and authority envelope.</p><p>Plan digest</p><p class="digest" data-plan-digest></p><p>Envelope digest</p><p class="digest" data-envelope-digest></p><div class="actions"><form data-action="approve-plan"><label class="field-label" for="plan-digest">Exact plan digest</label><input id="plan-digest" name="planDigest" required autocomplete="off" spellcheck="false" aria-describedby="digest-help"><label class="field-label" for="envelope-digest">Exact envelope digest</label><input id="envelope-digest" name="envelopeDigest" required autocomplete="off" spellcheck="false" aria-describedby="digest-help"><button class="primary" type="submit">Approve exact plan</button></form><form data-action="reject-plan"><label class="field-label" for="plan-reason">Rejection reason</label><input id="plan-reason" name="reason" required maxlength="2000"><button class="danger" type="submit">Reject plan</button></form></div></div></template>`;
